name: globemart
description: A futuristic shopping app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  http: ^1.2.0
  uuid: ^4.2.2

  # Hive (local DB)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1 # (dev dep but needed)
  
  # Location
  geolocator: ^10.1.0

  # Image picker for profile image
  image_picker: ^1.1.2

  # Local notification
  flutter_local_notifications: ^16.3.0

  # PDF generator & sharing
  pdf: ^3.11.0
  printing: ^5.12.0

  # Crypto for password hashing
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/profile.png
